// src/components/achievementsData.js
const achievementsData = [
  {
      id: 1,
      name: "Dr. Rupali Vairagade",
      date: "14th October 2024",
      achievement: "Delivered an insightful Tech Talk",
      details: "Delivered an insightful Tech Talk on “India Future Ready: Safety & Cybersecurity Planning Considerations” to Second-Year students from the Computer Engineering Department at K.J. Somaiya Polytechnic under the banner of SAKEC CyberPeace Center of Excellence The session, held on 14th October 2024, empowered students with key insights into the future of cybersecurity and strategies for ensuring safety in the evolving digital landscape.",
      link: "https://example.com/tech-talk",
      banner: "/img/achievements/rupalimaam.png"
  },
  {
      id: 2,
      name: "Dr. Nilakshi Jain",
      date: "28th August 2024",
      achievement: "Conducted an Expert talk Session on threat hunting",
      details: "AT CHANDIGARH UNIVERSITY, in collaboration with its CyberPeace Centre of Excellence under the AIT CSE department, conducted an Expert talk session on threat hunting. This session provided a deep dive into using advanced threat sensors, combining theoretical knowledge with practical cybersecurity skills.",
      link: "https://example.com/expert-talk",
       banner: "/img/achievements/session.jpg"
  },
  {
      id: 3,
    name: "Dr. Nilakshi Jain",
    date: "June 2024",
    achievement: "IT Engineer Panel",
    details: "Guided and uplifted society. She has been a part of the जैन युवा संघ मुंबई as an IT panelist, sharing insights and guiding aspiring engineers.",
    link: "https://example.com/it-panel",
    banner: "/img/achievements/itpanel.png",
  },
   {
       id: 4,
      name: "Dr. Nilakshi Jain",
      date: "30th – 31st August 2024",
      achievement: "𝐁𝐞𝐬𝐭 𝐇𝐨𝐃 𝐨𝐟 𝐭𝐡𝐞 𝐘𝐞𝐚𝐫",
      details: "CSI-E-TechNext 2024 Industry Academia Conference & Academia Awards (2024) based on the theme : Bridging the Future: Industry Vs Academia Digital Diversity Synergy on Emerging IT Ideas & Trends – Powered India’s New Education Policy",
      link: "https://example.com/hod-award",
      banner: "/img/achievements/besthod.png",
  },
   {
      id: 5,
      name: "CYSE Department",
      date: "July to Oct 2024",
      achievement: "Cybersecurity Awareness by Team Cyber Surksha Mandal",
      details: "Exposing Digital Deceptions: Skits on Deepfake Scams, Kidnapping Hoaxes, and Social Media Blackmail In a creative and powerful initiative, Team Cyber Surksha Mandal performed engaging skits to shed light on the alarming rise of deepfake technology, misinformation, and online fraud. Through compelling performances at schools, public spaces, and colleges",
      link: "https://example.com/awareness",
      banner: "/img/achievements/natak.png",
   },
  {
      id: 6,
     name: "CYSE Department",
    date: "July 2024",
    achievement: "Unveiling The magazine A Spectacular Launch",
     details: "Our magazine’s latest issue is set to revolutionize the way we confront the challenges of deepfake technology. With digital manipulation on the rise, it’s more important than ever to equip ourselves with the knowledge and tools to navigate this complex landscape",
    link: "https://example.com/magazine",
       banner: "/img/achievements/abhayan-2.jpg",
    },
  {
      id: 7,
      name: "Ms. Vishakha Shinde, CYSE",
      date: "July 2024",
      achievement: "Ms. Vishakha Shinde Assistant Professor Cyber Security Department. , has successfully earned the prestigious EC-Council’s Certified Cloud Security Engineer (C|CSE) certification",
       details:"The EC-Council’s C|CSE certification stands at the forefront of this transformation. This vendor-neutral certification highlights essential cloud security practices, technologies, and frameworks. Achieving this global certification requires immense dedication, hard work, and expertise in cloud computing.",
        link: "https://example.com/certified-cloud-security-engineer",
       banner: "/img/achievements/vishakha.jpg",
  },
  {
      id: 8,
    name: "Dr. Asha Durafe Dr. Rashmi Malvankar Uday Bhave Dr.Pravin Vishnu Shinde Atul Kachare Shubham Bakal Satish Bangal",
     date: "April 2024",
     achievement: "Conducted training for Navy officers",
      details:"Successfully conducted training for Navy officers in CCNA, Advanced SQL, and PHP under the supervision of Dr. Nilakshi Jain in SAKEC. Officers including LEM (R), LEM (P), LCOM(TEL), LS(GW), LAM, RPO, LPM, POME, PO(UW), LA (AH), POA (AH), LT CDR, and LT CDR-AT-ARMS participated in this training.",
    link: "https://example.com/navy-training",
      banner: "/img/achievements/navy.png",
  },
  {
    id: 9,
    name: "Council Members, CYSE",
      date:"April 2024",
     achievement:"Congratulated to the SAKEC Cyber Security Student Board members for their exceptional contributions throughout the academic year 2023-24",
     details:"Their dedication and hard work have undoubtedly made a significant impact.",
    link: "https://example.com/student-board",
    banner: "/img/achievements/council.png",
  },
  {
      id: 10,
     name: "SAKEC CyberPeace Center of Excellence",
      date:"13 Feb 2024",
      achievement: "SAKEC CyberPeace Center of Excellence was honored to host a distinguished delegation",
       details: "SAKEC CyberPeace Center of Excellence was honored to host a distinguished delegation comprising esteemed representatives from the Prime Minister’s Office, Sun Group Enterprises, and the Israel National Cyber Directorate (INCD). Dr. Nilakshi Jain, representing the SAKEC CyberPeace Centre of Excellence, had the privilege of showcasing our operations, state-of-the-art facilities, impactful contributions, and notable achievements. Students from SAKEC’s Cyber Security department presented their projects, showcasing their skills and innovative ideas. We express our gratitude for the insightful discussions and eagerly anticipate further engagements aimed at advancing cyber peace and security on a global scale.",
      link: "https://example.com/cyberpeace-center",
    banner: "/img/achievements/meeting.png",
  },
  {
      id: 11,
      name:"Atharva Auti, Dhruvil Jain, Mihir Doshi, and Vivek Mishra from the Cybersecurity Department",
      date:"April 6th, 2024",
      achievement: "SAKEC Cyber Security Team Triumphs at Cython 2024 Hackathon",
      details:"SAKEC Cyber Security Department Team (CyHEX Infotech Private Limited Start-up: https://cyhex.co/) has emerged victorious at the Cython 2024 Hackathon, held on April 6th, 2024, and organized by FITT-IIT Delhi. Our team has showcased remarkable talent and dedication, earning a prestigious win and a prize money of 3 Lakhs INR.",
    link: "https://example.com/hackathon",
     banner: "/img/achievements/cyhax-winner.jpg",
  },
  {
      id: 12,
      name:"CYSE Department",
      date:"April 2024",
       achievement: "Magazine Launch",
        details: "Industry Insights: From finance to entertainment, healthcare to education, each industry grapples with its own unique challenges when it comes to combating deepfake manipulation. Our Industry Insights segment sheds light on these nuances, offering expert perspectives and innovative strategies tailored to specific sectors.",
      link: "https://example.com/magazine-launch",
      banner: "/img/achievements/abhayan-2.jpg",
  },
   {
       id: 13,
      name:"Mustansir G. Yash Nagare Shubham Kolaskar Jayan Shah Pratham Shah CYSE students",
      date:"April 2024",
       achievement: "Successful completion of the project",
        details: "Introduce TrustTrace, the culmination of our students’ tireless efforts to combat the rising tide of deepfakes.",
      link: "https://example.com/project",
        banner: "/img/achievements/project.png",
  },
  {
      id: 14,
      name:"Dr. Shwetambari Borade",
     date:"26th February 2024",
      achievement: "Received an honorable German Patent",
       details: "Patent Title: “System for developing a deep scattering convolutional network for cosmetic skin classification” Patent Granted: 26th February 2024 Application No.: 20 2024 100 262.8",
      link: "https://example.com/german-patent",
     banner: "/img/achievements/patent.png",
  },
    {
        id: 15,
    name: "CYSE Student",
     date:"Jan 2024",
     achievement: "SAKEC students, faculties and external participants have shown great interest and exhibited remarkable performance in EC Council Certified Ethical Hackers (C|EH) course.",
     details: "The EC Council Certified Ethical Hackers (C|EH) V12 course has garnered outstanding interest and performance from our students, faculty, and external participants. Total of 24 candidates registered and 23 candidates successfully completed the certification.",
      link: "https://example.com/ethical-hackers",
      banner: "/img/achievements/ethical_hackers.png",
    },
    {
         id: 16,
      name:"Dr. Shwetambari Borade",
      date: "February 16, 2024",
       achievement: "Delivered a session at L&T Training Center, Madh Island, With a focus on fostering awareness about cybersecurity",
        details: "Dr. Borade engaged 25 trainers from Madhya Pradesh.The session, marked by its interactive nature, received exceptional acclaim from the participants. A testament to our commitment to advancing knowledge in the ever-evolving realm of cybersecurity.",
       link: "https://example.com/cybersecurity-awareness",
       banner: "/img/achievements/cybersecurity.png",
    },
     {
         id: 17,
      name:"Dr. Asha Durafe",
      date: "7th Feb 2024",
      achievement: "Delivered a session on Deepfake and Misinformation in AI Conclave, an AI conference sponsored by CyberPeaceat VIT, Bhopal!",
        details: "It was an enlightening experience for her to dive into the complexities and implications of this rapidly evolving field. From understanding the technical intricacies to discussing its impact on society, it’s crucial to stay informed and vigilant in this digital age.",
       link: "https://example.com/deepfake-session",
     banner: "/img/achievements/deepfake.png",
     },
   {
      id: 18,
    name: "CYSE Department",
      date:"8th Jan to 12 Jan 2024",
      achievement:"Completed STTP Successfully",
       details: "This industry academia venture opens a platform for students, faculty and industry professionals to learn from experts and earn international certifications in Cyber Security & Digital Forensics.",
       link: "https://example.com/sttp-training",
      banner: "/img/achievements/sttp.png",
  },
  {
      id: 19,
    name:"Tushar Patil, Pratham Poojari., Deepranjan Bhosale, and Aabha Wagh.",
    date: "Dec 2023",
    achievement: "Won First prize of Worth Rs. 1 lac Rupees",
    details: "Grand Finale of Smart India Hackathon 2023 conducted at Nodal center OP Jindal University Raigarh. Team was mentored by faculty Ms. Meghali kalyankar and Ms. Prajakta Pote.",
      link: "https://example.com/smart-india-hackathon",
    banner: "/img/achievements/hackathon2.png",
  },
  {
       id: 20,
    name: "Dr. Nilakshi Jain",
     date: "19th December 2023",
      achievement:"Dr. Nilakshi Jain, was invited as a distinguished panellist at the Round Table Consultation on Deepfake Technology",
        details:"This pivotal event, organized by the National Commission for Women – India (NCW) in collaboration with CyberPeace Foundation Collaborative, unfolded on December 19th, 2023, at the iconic Indian International Center in New Delhi.",
       link: "https://example.com/panellist-round-table",
       banner: "/img/achievements/panel.png",
  },
  {
       id: 21,
     name:"Dr. Nilakshi Jain",
     date: "October 2023",
    achievement:"Got research grant of 15 lacs",
    details:"Project “Investigating AI-Driven Misconduct: Deepfake Technology, Fake WhatsApp Calls, and Beyond” has secured a substantial research grant of 15 lacs.",
      link: "https://example.com/research-grant",
      banner: "/img/achievements/research.png",
  },
    {
        id: 22,
      name: "Dr. Nilakshi Jain",
      date: "Jan 2024",
       achievement: "Dr. Nilakshi Jain, a distinguished expert in the field of cybersecurity, was recently honored with an invitation to deliver a groundbreaking session on “Deepfake” at a prestigious workshop organized by UNSW, United Service Institution of India and CyberPeace Foundation.",
       details: "The workshop emphasized the potential role of Artificial Intelligence (AI) in addressing these challenges. Dr. Jain provided hands-on mitigatory techniques, equipping attendees with practical tools to navigate the complex terrain of misinformation and Deepfakes effectively.",
       link: "https://example.com/deepfake-workshop",
        banner: "/img/achievements/workshop.png",
   },
   {
       id: 23,
      name:"SAKEC TE Students",
     date: "9th Dec 2023",
      achievement:"1st Runner-Up at India’s renowned ‘Cffeine Trip’ hackathon!",
       details: "Congratulations to our Cybersecurity department’s students for securing 1st runner-up at India’s renowned ‘Cffeine Trip’ hackathon! Their innovative solutions and unwavering dedication underscore their prowess in defending digital frontiers. Congratulating students of Shah & anchor department’s pride: 1. Tanvi Humane (TE CYSE) 2. Akshat Adavadkar (TE CYSE)",
       link: "https://example.com/hackathon-runnerup",
        banner: "/img/achievements/hackathon_runnerup.png",
   },
  {
       id: 24,
      name:"SAKEC TE Students",
    date: "9th Dec 2023",
    achievement:"Winners at India’s renowned ‘Cffeine Trip’ hackathon!",
     details: "Exceptional achievement alert! Our Cybersecurity students emerge as champions at India’s longest hackathon, ‘Cffeine Trip’! Their ground-breaking solutions and unparalleled expertise set a new standard in cybersecurity. A proud moment for innovation and excellence! Congratulating students of Shah & anchor department’s pride: 1. Krishna Kounder (TE CYSE) 2. Sahil Zunjarrao (TE CYSE) 3. PAXAL DILIP TALAWAT (TE CYSE)",
       link: "https://example.com/hackathon-winners",
       banner: "/img/achievements/hackathon_winners.png",
   },
   {
        id: 25,
     name:"SAKEC TE Students",
      date:"9th Dec 2023",
     achievement: "Best Individual Performance at Grand Final  India’s renowned ‘Cffeine Trip’ hackathon!",
     details:"Individual:”Thrilled to congratulate Deepranjan Bhosale Bhosle from our Cybersecurity department for clinching the title of ‘Best Individual’ at ‘Cffeine Trip,’ India’s premier hackathon! His exceptional talent, innovation, and unwavering dedication to cybersecurity have set an inspiring benchmark. Kudos to their outstanding achievement!",
     link: "https://example.com/hackathon-individual",
      banner: "/img/achievements/hackathon_individual.png",
  },
  {
       id: 26,
    name:"SAKEC BE Students",
     date:"9th Dec 2023",
    achievement:"2nd runner-up at India’s renowned ‘Cffeine Trip’ hackathon!",
     details: "2nd Runner-Up: “Kudos to our Cybersecurity students for achieving 2nd runner-up at India’s prestigious ‘Cffeine Trip’ hackathon! Their dedication and skill in safeguarding digital realms shine bright, showcasing their commitment to excellence in cybersecurity. hashtag#CyberExcellence hashtag#Hackathon Achievement” Congratulating students of Shah & anchor department’s pride: 1. Shreyansh Dave (BE CYSE) 2. Aishwarya Kadam (BE CYSE)",
    link: "https://example.com/hackathon-second-runnerup",
       banner: "/img/achievements/hackathon_runnerup2.png",
   },
    {
         id: 27,
      name:"SAKEC TE and BE Students",
     date:"1st September, 2023",
      achievement:"Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India",
      details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name:  Linux Admin",
      link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/global_cyberpeace_summit.png"
      },
  {
       id: 28,
      name:"SAKEC TE and BE Students",
      date:"1st September, 2023",
      achievement:"Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India",
      details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi. Project Name: HoneyTrack",
      link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/global_cyberpeace_summit.png"
  },
  {
      id: 29,
      name:"SAKEC BE Students",
        date:"1st September, 2023",
      achievement:"Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India",
       details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name:Cygiene",
     link: "https://example.com/global-cyberpeace-summit",
     banner:"/img/achievements/global_cyberpeace_summit.png"
  },
      {
         id: 30,
       name:"SAKEC BE Students",
        date:"1st September, 2023",
        achievement:"Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India",
       details: "SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name: courage2correct",
        link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/global_cyberpeace_summit.png"
    },
  {
      id: 31,
    name:"SAKEC TE and BE Students",
       date: "1st September, 2023",
      achievement:"Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India",
       details:"SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi Project Name: Capture The Flag",
        link: "https://example.com/global-cyberpeace-summit",
       banner:"/img/achievements/global_cyberpeace_summit.png"
  },
  {
       id: 32,
    name:"SAKEC TE and BE Students",
      date:"1st September, 2023",
      achievement: "Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India",
       details: "SAKEC CyberPeace Centre of Excellence proud to announce that our Research based project got launched in Global CyberPeace Summit and Dialogues a pivotal event supporting G20 India on 1st September, 2023 in United Service Institution, Rao Tula Ram Marg, New Delhi. Project Name : Dark Web",
       link: "https://example.com/global-cyberpeace-summit",
     banner:"/img/achievements/global_cyberpeace_summit.png"
   },
   {
       id: 33,
     name:"Rammya Sakpal Rushikesh Patil Prerana Patil",
     date: "Sept 2023",
      achievement:"Winners received prizes worth $1,000 and an Intel certificate.",
       details:"Cyber Security Department Students achieved remarkable success as a Country/Region Winner in the prestigious Intel® AI Global Impact Festival 2023! Winners received prizes worth $1,000 and an Intel certificate. their outstanding AI project has not only showcased their immense talent but has also made a significant contribution to the world of artificial intelligence & cyber security.",
     link: "https://example.com/intel-ai-festival",
     banner:"/img/achievements/ai_festival.png"
    },
    {
        id: 34,
      name:"Industrial visit",
      date:"26th July 2023",
       achievement:"Industrial visit at AIIPLTECH PVT. LTD Vashi, Navi Mumbai",
       details:"Highlights of the Visit: Engaging presentations on Cyber Security trends and challenges Live demonstrations of state-of-the-art security solutions Networking opportunities with industry professionals Interactive Q&A sessions with Cyber Security specialists",
        link: "https://example.com/industrial-visit",
     banner: "/img/achievements/industrial_visit.png",
  },
   {
       id: 35,
     name: "Shrawani JS Pagar, from the Cyber Security department at SAKEC College",
      date:"24th August 2023",
     achievement: "On behalf of V4WEB CYBERSECURITY, Shrawani recently conducted an enlightening and impactful training session for none other than the esteemed Indian Airforce, focusing on “Cybersecurity Awareness.”",
      details: "Shrawani’s training session was a resounding success, receiving accolades from the Indian Air Force for her expertise and dedication to the field of cybersecurity.",
     link: "https://example.com/indian-airforce-training",
    banner: "/img/achievements/airforce.png",
  },
  {
       id: 36,
       name:"Mr. Mustansir G. from CyberPeace CCoE at SAKEC",
      date:"10th to 13th June 2023",
     achievement: "Invited as a Technical Team member of the prestigious CCTNS HACKATHON & CYBER CHALLENGE 2023 (4th Edition) in collaboration with the National Crime Record Bureau, Ministry of Home Affairs, Govt. of India!",
      details:"Mr. Mustaansir Godhrawala contributed his expertise as a member of the technical team, engaging with brilliant minds in cybersecurity and witnessing cutting-edge solutions.",
     link: "https://example.com/cctns-hackathon",
    banner: "/img/achievements/cctns.png",
  },
     {
        id: 37,
      name:"Atharva Auti, Dhruvil Jain, Mihir Doshi, and Vivek Mishra from the Cybersecurity Department",
         date:"16th March 2023",
      achievement:"Launched their startup named CyHEX Infotech Private Limited.",
       details: "Startup is all about providing development, products, and services that make a difference.  Every project is unique, and they work closely with their clients to understand their needs and deliver customized solutions. Thier goal is to make technology accessible and easy for everyone.",
      link: "https://example.com/cyhex-infotech",
     banner: "/img/achievements/startup.png",
    },
  {
       id: 38,
    name:"Dr. Nilakshi Jain",
      date:"July 2023",
    achievement: "Shortlisted for the highly esteemed Cybersecurity Woman of the Year Awards 2023, Cybersecurity Alliance.",
    details: "Her exceptional talent, dedication, and significant contributions to the field of cybersecurity have earned her a place among an exceptional group of women. This year’s awards have surpassed all expectations, attracting an unprecedented number of outstanding nominees from around the world. From New Zealand to Moldova, Macedonia to Ukraine, Philippines to Egypt, Kuwait to Australia, Italy to the Netherlands, Zimbabwe to Peru, and over 60 other remarkable countries, the diversity and global impact of women in cybersecurity shine brightly.",
    link: "https://example.com/cybersecurity-woman",
   banner: "/img/achievements/women_cybersecurity.png",
  },
   {
      id:39,
      name:"Cyber security Department magazine, Abhayam!",
    date:"25th April 2023",
     achievement: "Successful inauguration of CyberSpace Coding lab & launch of our first-ever cyber security Department magazine, Abhayam!",
      details:"Event was held on 25th April 2023 in the presence of respected Trustees, Principal Dr Bhavesh Patel ,HoDs , faculties, and Cyber Security Council members.",
     link: "https://example.com/magazine-abhayam",
     banner:"/img/achievements/abhayam.png",
   },
  {
       id: 40,
      name:"CEH Certified Faculty, Student and External participants",
     date:"Jan 2023",
       achievement: "SAKEC students, faculties and external participants have shown great interest and exhibited remarkable performance in EC Council Certified Ethical Hackers (C|EH) course.",
      details:"Total of 27 candidates registered and 25 candidates successfully completed the certification.",
      link: "https://example.com/ceh-participants",
      banner: "/img/achievements/ceh.png",
  },
  {
      id: 41,
    name:"Deep Parasiya , Jasjyot Singh Saini Chirag P. from Second Year",
     date: "Jan 2023",
    achievement:"Secured 1st Position in the CTF challenge CYBER HEIST, Resonance 2023",
     details:"The team was awarded with a certificate and cash prize. Organized by S.I.W.S College Wadala, Mumbai.",
   link:"https://example.com/ctf-challenge",
   banner: "/img/achievements/ctf_challenge.png",
 },
 {
        id: 42,
      name: "Dr. Nilakshi Jain",
      date: "19 May 2022",
      achievement: "Scored 91 percent at the certification exam Certified Hacking Forensic Investigator (CHFI) and being awarded the EC council Scholarship worth RS. 48,750.",
        details: "EC-Council",
        link: "https://example.com/chfi-certification",
    banner: "/img/achievements/chfi.png",
    },
];

export default achievementsData;